# Generated by Django 2.0 on 2019-12-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='article_name', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'articles',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(db_column='username', max_length=100),
        ),
    ]
