# Generated by Django 2.0 on 2019-12-11 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20191211_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['txt', 'md', 'jpg', 'wmv'], message='缩略图必须是指定格式的文件')]),
        ),
    ]
