# Generated by Django 2.0 on 2019-12-09 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['price']},
        ),
    ]
