# Generated by Django 2.0 on 2019-12-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_auto_20191209_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookorder',
            options={'ordering': ['-price']},
        ),
    ]
