# Generated by Django 2.0 on 2019-12-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(to='article.Article'),
        ),
    ]
