# Generated by Django 2.0 on 2019-12-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20191206_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', related_query_name='art', to='frontuser.FrontUser'),
        ),
    ]
